### PR TITLE
quark file: remove \helpdoc entry

### PR DESCRIPTION
**Pull request by jaschanarveson**
Removed the entry for \helpdoc from the quark file (ie: the entry that pointed to the old help.html file that no longer exists).

### CODE REVIEW

**Comment by nhthn** [comment]
This PR contains all the commits from #3. You're going to want to cherrypick the intended change for this PR into a new branch.

It probably doesn't matter in this case but we try to avoid merging things with weird commit histories. See https://github.com/supercollider/supercollider/pull/1918.

**Comment by jaschanarveson** [comment]
Yeah - I'm new to GitHub (obviously) and not great at the workflow yet.  Any advice on how I should clean up my more recent PRs?  Can I remove PRs and re-submit them from nicely separated branches?

**Comment by nhthn** [comment]
No worries, git is a complex beast and I still have trouble with it now and then :) The GitHub web interface is suitable for some basic edits, but for more advanced things you'll want to use the command line. There are plenty of tutorials out there. [This blog post](https://eev.ee/blog/2015/04/24/just-enough-git-to-be-less-dangerous/) is great if you want a bit of theory.

In this case, a cherrypick is in order. Mind if I take care of it?

**Comment by nhthn** [comment]
whoa, you deleted your fork! I can't cherrypick it now :/

**Comment by jaschanarveson** [comment]
Ha!  Yes - i acted too soon.  I tried to delete my fork and re-clone a clean copy from the original, but my newly forked Conductor kept all my old changes (?!).  So, this is a bit of a cluster-bomb of commits (which i know how to avoid in future!), but my new note in the new PR explains things pretty well, hopefully.

**Comment by jaschanarveson** [comment]
Hi, again -  

I don't know if you get replies to a closed thread - the PR's back up if you have time to take a look?

cheers,

j

**Comment by nhthn** [comment]
haven't looked at it yet, sorry

**Comment by jaschanarveson** [comment]
No worries - just wanted to make sure my last message actually got to you.  

cheers,

j

**Pull request closed without merging**
